### DISCUSSION TITLE
Deploy powersync service into Azure WebApp

### DISCUSSION THREAD

**Discussion by Rotarex-Guillaume-Michael** [powersync-ja/powersync-service#101] [Q&A] [answered]
Has someone already deploy powersync service into an Azure WebApp ?

I am struggling so much to do it because of "pnpm" and some slowdown of Azure WebApp to build the project with oryx

Right now, I have added the following in package.json than I use the vscode azure extension to publish in the web app. But it can take up to 40 minutes for azure web app ro run with oryx build .... Unusable in production :(

![image](https://github.com/user-attachments/assets/8ef79de1-c465-4cb8-b975-299382a1491b)

```
"preinstall": "npm install -g pnpm",
"start": "npm install -g pnpm && pnpm install && pnpm start:service",
```

I tried also to deploy in Azure container app wich is a container host without success either 

Any help ?

**Comment by rkistner** [comment]
I wouldn't recommend building the container from scratch. While you can technically do that, using the pre-built container image is much simpler and faster.

What issues did you run into with Azure Container Apps?

Azure Web App for Containers is another option, but I don't have enough experience myself to comment on the pros/cons between the two.

**Comment by Rotarex-Guillaume-Michael** [comment]
Azure container apps is good to simplify the communication/monitoting of multiple service (Containers) working together, it also super easy to manage multiple version of a single container. 

I can also use Azure web App but following your [documentation](https://docs.powersync.com/self-hosting/installation/powersync-service-setup#powersync-configuration), I am not able to provide environment variables, any idea how I could do that ? 

![image](https://github.com/user-attachments/assets/f115cb13-e68e-4373-a30b-5a75952f90bb)

**Reply by Rotarex-Guillaume-Michael** [reply]
I found that I can [mount a storage to the azure web app linux container ](https://learn.microsoft.com/en-us/azure/app-service/configure-connect-to-azure-storage?tabs=basic%2Cportal&pivots=container-linux), I need to find out how to put everything together ... 

any advice ?

![image](https://github.com/user-attachments/assets/237c59d5-ab62-4a83-a8b2-aaea402eff2c)


![image](https://github.com/user-attachments/assets/74681f36-8703-4a4b-a6eb-d6635830e9e5)

**Reply by rkistner** [reply]
You generally don't need to mount any storage for the powersync container. Typically that is needed when the container needs to write to the storage - in this case you only want to deploy config with the container.

I'm not sure exactly how that is done with Azure Web App Containers, I'll see if we can get someone to help. Specifying the entire config as a base-64-encoded environment variable is probably the simplest option.

**Reply by Rotarex-Guillaume-Michael** [reply]
What would be the environment variable name ? Is it "POWERSYNC_CONFIG_B64" ? So i should just put this variable name and the content would be the "powersync_config" file base64 encoded ?

**Reply by rkistner** [reply]
Yes, that's correct.

You can see our example [here](https://docs.powersync.com/self-hosting/installation), using the base64 command (linux/macos) to encode the config file: 
> POWERSYNC_CONFIG_B64="$(base64 -i ./config.yaml)"

I'd recommend trying this locally with Docker first, before deploying on Azure.

**Comment by Rotarex-Guillaume-Michael** [comment, marked as answer]
Thank you for your help, here is a working infrastructure:

![image](https://github.com/user-attachments/assets/9f75d7ae-2932-4f0c-b315-de7e9f77f0b1)

During my test, I had to update the timeout duration, it's shouldn't be necessary

It's in seconds:
> WEBSITES_CONTAINER_START_TIME_LIMIT: 1800  

You must put the configuration in base64 encoded format (I used [devtoys](https://devtoys.app/) for that but anything that can encode the config file in base 64 works

> POWERSYNC_CONFIG_B64: IyBwb3dlcnN5bmMueWFtbA0KIyBWZXJ5IHNpbWlsYXIgdG8gdGhlIGNvbmZpZyBvbiBDb2xsaWRlLCBidXQgYSBsaXR0bGUgbW9yZSBsb3ctbGV2ZWwNCiMgU2 ..........

So for example, the following config file 


```
# powersync.yaml
# Very similar to the config on Collide, but a little more low-level
# See https://github.com/powersync-ja/powersync-service/blob/c6140e883a4a2ac9c8c2e46b7c31ad38e1c6d28a/packages/types/src/config/PowerSyncConfig.ts#L95

migrations:
  disable_auto_migration: false

replication:
  connections:
    - type: postgresql
      uri: postgres://{userName}:{password}@{postGresHostname}/{postGresDatabaseName}
      # sslmode: disable # okay for local/private network, not for public network

storage:
  type: mongodb
  uri: mongodb+srv://{userName}:{password}@{clusterName}.pkosg.mongodb.net/{databaseName}?retryWrites=true&w=majority&appName={appName}
  username: {userName}
  password: 
  # uri: mongodb://localhost:27017/powersync_demo

port: 8080


# Client (application end user) authentication settings
client_auth:
  # Enable this if using Supabase Auth
  # supabase: true

  # JWKS URIs can be specified here
  jwks_uri: https://{jwtHostnameService}/api/auth/keys
  # jwks_uri: http://localhost:6060/api/auth/keys

  # JWKS audience
  audience: ['powersync-dev', 'powersync']

# Specify sync rules
sync_rules:
  content: |
    bucket_definitions:
      global:
        data:
          - SELECT * FROM lists
          - SELECT * FROM todos
```

would give the following base64 content to put in the ' POWERSYNC_CONFIG_B64' variable

> IyBwb3dlcnN5bmMueWFtbA0KIyBWZXJ5IHNpbWlsYXIgdG8gdGhlIGNvbmZpZyBvbiBDb2xsaWRlLCBidXQgYSBsaXR0bGUgbW9yZSBsb3ctbGV2ZWwNCiMgU2VlIGh0dHBzOi8vZ2l0aHViLmNvbS9wb3dlcnN5bmMtamEvcG93ZXJzeW5jLXNlcnZpY2UvYmxvYi9jNjE0MGU4ODNhNGEyYWM5YzhjMmU0NmI3YzMxYWQzOGUxYzZkMjhhL3BhY2thZ2VzL3R5cGVzL3NyYy9jb25maWcvUG93ZXJTeW5jQ29uZmlnLnRzI0w5NQ0KDQptaWdyYXRpb25zOg0KICBkaXNhYmxlX2F1dG9fbWlncmF0aW9uOiBmYWxzZQ0KDQpyZXBsaWNhdGlvbjoNCiAgY29ubmVjdGlvbnM6DQogICAgLSB0eXBlOiBwb3N0Z3Jlc3FsDQogICAgICB1cmk6IHBvc3RncmVzOi8ve3VzZXJOYW1lfTp7cGFzc3dvcmR9QHtwb3N0R3Jlc0hvc3RuYW1lfS97cG9zdEdyZXNEYXRhYmFzZU5hbWV9DQogICAgICAjIHNzbG1vZGU6IGRpc2FibGUgIyBva2F5IGZvciBsb2NhbC9wcml2YXRlIG5ldHdvcmssIG5vdCBmb3IgcHVibGljIG5ldHdvcmsNCg0Kc3RvcmFnZToNCiAgdHlwZTogbW9uZ29kYg0KICB1cmk6IG1vbmdvZGIrc3J2Oi8ve3VzZXJOYW1lfTp7cGFzc3dvcmR9QHtjbHVzdGVyTmFtZX0ucGtvc2cubW9uZ29kYi5uZXQve2RhdGFiYXNlTmFtZX0/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9e2FwcE5hbWV9DQogIHVzZXJuYW1lOiB7dXNlck5hbWV9DQogIHBhc3N3b3JkOiANCiAgIyB1cmk6IG1vbmdvZGI6Ly9sb2NhbGhvc3Q6MjcwMTcvcG93ZXJzeW5jX2RlbW8NCg0KcG9ydDogODA4MA0KDQoNCiMgQ2xpZW50IChhcHBsaWNhdGlvbiBlbmQgdXNlcikgYXV0aGVudGljYXRpb24gc2V0dGluZ3MNCmNsaWVudF9hdXRoOg0KICAjIEVuYWJsZSB0aGlzIGlmIHVzaW5nIFN1cGFiYXNlIEF1dGgNCiAgIyBzdXBhYmFzZTogdHJ1ZQ0KDQogICMgSldLUyBVUklzIGNhbiBiZSBzcGVjaWZpZWQgaGVyZQ0KICBqd2tzX3VyaTogaHR0cHM6Ly97and0SG9zdG5hbWVTZXJ2aWNlfS9hcGkvYXV0aC9rZXlzDQogICMgandrc191cmk6IGh0dHA6Ly9sb2NhbGhvc3Q6NjA2MC9hcGkvYXV0aC9rZXlzDQoNCiAgIyBKV0tTIGF1ZGllbmNlDQogIGF1ZGllbmNlOiBbJ3Bvd2Vyc3luYy1kZXYnLCAncG93ZXJzeW5jJ10NCg0KIyBTcGVjaWZ5IHN5bmMgcnVsZXMNCnN5bmNfcnVsZXM6DQogIGNvbnRlbnQ6IHwNCiAgICBidWNrZXRfZGVmaW5pdGlvbnM6DQogICAgICBnbG9iYWw6DQogICAgICAgIGRhdGE6DQogICAgICAgICAgLSBTRUxFQ1QgKiBGUk9NIGxpc3RzDQogICAgICAgICAgLSBTRUxFQ1QgKiBGUk9NIHRvZG9z

`

As you can see in devtoys:

![image](https://github.com/user-attachments/assets/30c47fe2-563f-48ac-bddd-a02009af8ee6)


And here are the environment variables

![image](https://github.com/user-attachments/assets/f4c6fa07-796f-497f-8522-ddf67c92008e)

and I pulled the image from my owner container registries as I had limitation with docker hub  (I couldn't pull more thant 100 image per hours)

![image](https://github.com/user-attachments/assets/98771525-d1f5-4815-a902-8f95b03c476d)

Hope it can help someone ! 

Thank for your valuable advices and your great job !
