### DISCUSSION TITLE
Healthcheck API

### DISCUSSION THREAD

**Discussion by JCKodel** [powersync-ja/powersync-service#62] [General]
Sometimes, Powersync is in an invalid state and not much information is sent to the client about why.

For example:

```
{"level":"error","message":"Replication error Publication 'powersync' does not exist. Run: `CREATE PUBLICATION powersync FOR ALL TABLES`, or read the documentation for details."
...
```

It also stays in an invalid state when something is wrong with `sync_rules.yaml` (I see the exactly reason only on docker desktop logs panel).

It would be nice a `GET` endpoint to check if there is any error in the service and returning `200` or `500`.

That could be used in docker compose `healthcheck`.

**Comment by stevensJourney** [comment]
There currently is an undocumented admin API route which might help with this.

A `POST` request to `http://localhost:8080/api/admin/v1/diagnostics` should return some diagnostics information. The authentication is provided with a predefined set of admin tokens.

In the config YAML file you can define the tokens:
``` yaml
api:
  tokens:
    - [super secret token]
```

Then you can use a defined token in the `Authorization` header of the request.

```bash
curl -X POST http://localhost:8080/api/admin/v1/diagnostics \
     -H "Authorization: Bearer [super secret token]" \
     -H "Content-Type: application/json" \
     -H "Accept: application/json" \
     -d '{}'
```

**Comment by JCKodel** [comment]
@stevensJourney Thank you.

For those interested in, that's what I got:

```yaml
healthcheck:
  test: 'curl -X POST http://localhost:${PS_PORT}/api/admin/v1/diagnostics -H "Authorization: Bearer ${PS_API_TOKEN}" -H "Content-Type: application/json" -H "Accept: application/json" -d "{}" | grep "\"errors\":\[{" && exit 1 || exit 0'
  interval: 5s
  timeout: 1s
  retries: 15
```

**Reply by guillempuche** [reply]
Hi, you put `healthcheck` in the config.yml, right?

**Reply by JCKodel** [reply]
Nop. In docker-compose.yaml.

**Reply by guillempuche** [reply]
Cool. Something like:

```yml
services:
  powersync:
    image: journeyapps/powersync-service:latest
    command: ["start", "-r", "unified",]
    depends_on:
      mongo-rs-init:
        condition: service_completed_successfully
    environment:
      POWERSYNC_CONFIG_PATH: /config/config.yml
      PS_POSTGRES_URI: postgresql://postgres:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      PS_API_TOKEN: abcd1234
      PS_PORT: 8080
    networks:
      - supabase_network
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - ./config.yml:/config/config.yml
      - ./sync_rules.yml:/config/sync_rules.yml
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: 'curl -X POST http://localhost:${PS_PORT}/api/admin/v1/diagnostics -H "Authorization: Bearer ${PS_API_TOKEN}" -H "Content-Type: application/json" -H "Accept: application/json" -d "{}" | grep "\"errors\":\[{" && exit 1 || exit 0'
      interval: 5s
      timeout: 1s
      retries: 15
   ...
```

**Comment by DominicGBauer** [comment]
Hi @JCKodel and @guillempuche you can now use the `/probes/liveness` endpoint for your healthchecks :). 

Example below:
```
# This requires image: journeyapps/powersync-service:0.5.8 or later
     healthcheck:
       test: ["CMD", "node", "-e", "fetch('http://localhost:${PS_PORT}/probes/liveness').then(r => r.ok ? process.exit(0) : process.exit(1)).catch(() => process.exit(1))"]
       interval: 5s
       timeout: 1s
       retries: 15
```
