### ISSUE TITLE
[Feature] Create an online Sync Rules validator

### ISSUE THREAD

**Issue by guillempuche** [powersync-ja/powersync-service#103]
It's very helpful to thinker in the localhost, but not for sync rules. To know if they're valid, right now the best way is to do it in your hosted cloud, I prefer to only touch the cloud when it's ready.

![imatge](https://github.com/user-attachments/assets/7296419c-8764-4b30-9bf3-85bd01b5a6fe)

I suggest you to create an online validator (like https://jsonformatter.org/, or playgrounds https://dart.dev/#try-dart). It should allow passing the SQL script (with all the schemas) and sync rules.

**Comment by stevensJourney** [comment]
This is not yet documented, but it is possible to perform sync rules validation via an API request to your local PowerSync service.

An authentication token needs to be configured in your PowerSync configuration file. See [here](https://github.com/powersync-ja/powersync-service/discussions/62#discussioncomment-10415553) for details.

An Example cURL request is below

```sh
curl -X POST http://localhost:8080/api/sync-rules/v1/validate \
-H "Authorization: Bearer [YOUR_TOKEN]" \
-H "Content-Type: application/yaml" \
--data-binary "@./sync_rules.yaml"
```

We will track the remaining requests on our Product board.

**Comment by guillempuche** [comment]
When running it, I don't get the outcome in my terminal, I need to open PowerSync service Docker logs. You could improve this to give back the outcome in a nice format.

```sh
curl -X POST http://localhost:8080/api/sync-rules/v1/validate \
-H "Authorization: Bearer [token]" \
-H "Content-Type: application/yaml" \
--data-binary "@./sync_rules.yaml"
curl: Failed to open ./sync_rules.yaml
curl: option --data-binary: error encountered when reading a file
curl: try 'curl --help' or 'curl --manual' for more information
```

**Comment by stevensJourney** [comment]
The response should be printed if a valid path to a Sync rules file is provided. The error above is coming from cURL. Please update the path in `--data-binary` to point to your Sync Rules YAML file. 

<img width="838" alt="image" src="https://github.com/user-attachments/assets/a906d66e-b60a-48ac-8345-0daa6255d643">

**Comment by guillempuche** [comment]
It works.

My `config.yml`:
```yml
# Documentation: https://docs.powersync.com/self-hosting/local-development

replication:
  connections:
    - type: postgresql
      uri: !env PS_POSTGRES_URI

      # SSL settings
      sslmode: disable # 'verify-full' (default) or 'verify-ca' or 'disable'

# Connection settings for sync bucket storage
storage:
  type: mongodb
  uri: mongodb://mongo:27017/powersync_demo

# The port which the PowerSync API server will listen on
port: 8080

sync_rules:
  path: /config/sync_rules.yml

client_auth:
  # Enable this if using Supabase Auth
  supabase: true

  # JWKS URIs can be specified here if you were using a custom setup
  # jwks_uri: [TODO]  # This is not needed when supabase: true is set

  # Optional static collection of public keys for JWT verification
  jwks:
    #   keys:
    #     - kty: 'RSA'
    #       n: !env PS_JWK_N
    #       e: !env PS_JWK_E
    #       alg: 'RS256'
    #       kid: !env PS_JWK_KID
    keys:
      - kty: "oct"
        k: "thisisonlyforthediagnosticsappandshouldnotbeusedinproduction"
        alg: "HS256"

  # JWKS audience
  audience: ["powersync-dev", "powersync"]

# Settings for telemetry reporting
# See https://docs.powersync.com/self-hosting/telemetry
telemetry:
  # Opt out of reporting anonymized usage metrics to PowerSync telemetry service
  disable_telemetry_sharing: false

api:
  tokens:
    - abcd1234
```
