### ISSUE TITLE
About sync_rules bucket parameters

### ISSUE THREAD

**Issue by JCKodel** [powersync-ja/powersync-service#60]
My scenario: I have a `users` table, a `companies` table and a `company_users` table where I add users to companies.

My sync_rules.yaml is:

```yaml
bucket_definitions:
  user_data:
    parameters: 
      - SELECT token_parameters.user_id as user_id
      - SELECT company_id FROM company_users WHERE user_id = token_parameters.user_id
    data:
      - SELECT * FROM users WHERE id = bucket.user_id
      - SELECT * FROM user_settings WHERE user_id = bucket.user_id
      - SELECT * FROM company_users WHERE user_id = bucket.user_id
      - SELECT * FROM companies WHERE owner_id = bucket.user_id or id = bucket.company_id
```

Problem is: a user can be in more than one company, so `SELECT company_id FROM company_users WHERE user_id = JWT` can return more than one result.

Given the bucket data fetches all companies where `id` equals the `company_id` above, it will return all companies, only the first, the whole thing will fail?

If this requires an `IN` where clause, how it can be written?

Documentation is very vague in sync_rules regard =\

Thanks in advance

**Comment by stevensJourney** [comment]
You can have multiple `parameter` queries in the same bucket definition, but the parameter names must be the same over all of them, which is not the case here since `user_id` != `company_id`.

Our dashboard should show an error if these sync rules were input there. But we currently don't have linting for self hosted cases.

You should be able to achieve your desired result by implementing two bucket definitions:

```yaml
  user_data:
    parameters: 
        - SELECT token_parameters.user_id as user_id
    data:
        - SELECT * FROM users WHERE id = bucket.user_id
        - SELECT * FROM user_settings WHERE user_id = bucket.user_id
        - SELECT * FROM company_users WHERE user_id = bucket.user_id
        - SELECT * FROM companies WHERE owner_id = bucket.user_id
        
  user_companies:
    parameters: 
        - SELECT company_id FROM company_users WHERE user_id = token_parameters.user_id
    data:
         - SELECT * FROM companies WHERE id = bucket.company_id
```
