### ISSUE TITLE
Add healthcheck API

### ISSUE THREAD

**Issue by JCKodel** [powersync-ja/powersync-service#61]
Sometimes, Powersync is in an invalid state and not much information is sent to the client about why.

For example:

```
{"level":"error","message":"Replication error Publication 'powersync' does not exist. Run: `CREATE PUBLICATION powersync FOR ALL TABLES`, or read the documentation for details."
...
```

It also stays in an invalid state when something is wrong with `sync_rules.yaml` (I see the exactly reason only on docker desktop logs panel).

It would be nice a `GET` endpoint to check if there is any error in the service and returning `200` or `500`.

That could be used in docker compose `healthcheck`.

**Comment by stevensJourney** [comment]
There currently is an undocumented admin API route which might help with this.

A `POST` request to `http://localhost:8080/api/admin/v1/diagnostics` should return some diagnostics information. The authentication is provided with a predefined set of admin tokens.

In the config YAML file you can define the tokens:
``` yaml
api:
  tokens:
    - [super secret token]
```

Then you can use a defined token in the `Authorization` header of the request.

```bash
curl -X POST http://localhost:8080/api/admin/v1/diagnostics \
     -H "Authorization: Bearer [super secret token]" \
     -H "Content-Type: application/json" \
     -H "Accept: application/json" \
     -d '{}'
```

**Comment by JCKodel** [comment]
@stevensJourney Thank you.

For those interested in, that's what I got:

```yaml
healthcheck:
  test: 'curl -X POST http://localhost:${PS_PORT}/api/admin/v1/diagnostics -H "Authorization: Bearer ${PS_API_TOKEN}" -H "Content-Type: application/json" -H "Accept: application/json" -d "{}" | grep "\"errors\":\[{" && exit 1 || exit 0'
  interval: 5s
  timeout: 1s
  retries: 15
```
